
spring:
 cloud.compatibility-verifier.enabled: false
 application.name: demo-jpa-platform
 main.allow-circular-references: true
 main.allow-bean-definition-overriding: true
 datasource:
   url: jdbc:h2:mem:testdb
   username: sa
   password: 
   driverClassName: org.h2.Driver
 jpa:
      open-in-view: false
      properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
      hibernate.ddl-auto: update
      properties:
        hibernate:
          format_sql: false
          show_sql: true
        

onesaitplatform:
   iotclient:  
    token: 3b8a25fe233b4a45a19d1308bbb9073a
    deviceTemplate: client
    device: client
    urlRestIoTBroker: https://development.onesaitplatform.com
   notifierclient:
    enabled: true
    server: https://development.onesaitplatform.com
    username: fjgcornejo
    password: 
    apikey: 5e29a14ab02c4cc08a404e71358d9bd5
